default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: rootpassword
  host: db
  port: 3306
  timeout: 5000

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: your_app_name_test

production:
  <<: *default
  database: your_app_name_production
  username: your_production_mysql_username
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: your_production_mysql_host
